services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-aggregator
    container_name: news-aggregator
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: news-aggregator
      DB_USERNAME: admin
      DB_PASSWORD: P@ssword!
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: news-aggregator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssword!
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: